// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "netutils.h"

Fl_Browser *brwsCallsign=(Fl_Browser *)0;

Fl_Button *btnCancelCallsignSearch=(Fl_Button *)0;

Fl_Button *btn_OkCallsignSearch=(Fl_Button *)0;

Fl_Double_Window* winCallsignBrowse() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(304, 231, "Browse by Callsign");
    w = o;
    o->color(FL_LIGHT2);
    { brwsCallsign = new Fl_Browser(0, 0, 215, 230);
      brwsCallsign->type(2);
      brwsCallsign->textfont(13);
      brwsCallsign->when(FL_WHEN_RELEASE);
    } // Fl_Browser* brwsCallsign
    { btnCancelCallsignSearch = new Fl_Button(230, 35, 60, 40, "Cancel");
      btnCancelCallsignSearch->callback((Fl_Callback*)cb_btnCancelCallsignSearch);
    } // Fl_Button* btnCancelCallsignSearch
    { btn_OkCallsignSearch = new Fl_Button(230, 135, 60, 40, "OK");
      btn_OkCallsignSearch->callback((Fl_Callback*)cb_OkCallsignSearch);
    } // Fl_Button* btn_OkCallsignSearch
    o->set_modal();
    o->end();
  } // Fl_Double_Window* o
  return w;
}

Fl_Browser *brwsNetNbr=(Fl_Browser *)0;

Fl_Button *btnCancelNetNbrSearch=(Fl_Button *)0;

Fl_Button *btn_OkNetNbrSearch=(Fl_Button *)0;

Fl_Double_Window* winNetNbrBrowse() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(300, 230, "Browse by Net Nbr");
    w = o;
    o->color(FL_LIGHT2);
    { brwsNetNbr = new Fl_Browser(0, 0, 215, 230);
      brwsNetNbr->type(2);
      brwsNetNbr->textfont(4);
      brwsNetNbr->when(FL_WHEN_RELEASE);
    } // Fl_Browser* brwsNetNbr
    { btnCancelNetNbrSearch = new Fl_Button(225, 45, 60, 40, "Cancel");
      btnCancelNetNbrSearch->callback((Fl_Callback*)cb_btnCancelNetNbrSearch);
    } // Fl_Button* btnCancelNetNbrSearch
    { btn_OkNetNbrSearch = new Fl_Button(225, 120, 60, 40, "OK");
      btn_OkNetNbrSearch->callback((Fl_Callback*)cb_OkNetNbrSearch);
    } // Fl_Button* btn_OkNetNbrSearch
    o->set_modal();
    o->end();
  } // Fl_Double_Window* o
  return w;
}

Fl_Double_Window *winSearchCallsignDialog=(Fl_Double_Window *)0;

Fl_Input *sSrchPrefix=(Fl_Input *)0;

Fl_Input *sSrchArea=(Fl_Input *)0;

Fl_Input *sSrchSuffix=(Fl_Input *)0;

Fl_Button *btnSearchCancel=(Fl_Button *)0;

Fl_Return_Button *btnSearchOK=(Fl_Return_Button *)0;

Fl_Double_Window* newSearchCallsignDialog() {
  { winSearchCallsignDialog = new Fl_Double_Window(207, 107);
    { sSrchPrefix = new Fl_Input(40, 35, 25, 25, "Prefix");
      sSrchPrefix->textfont(13);
      sSrchPrefix->align(Fl_Align(FL_ALIGN_TOP));
    } // Fl_Input* sSrchPrefix
    { sSrchArea = new Fl_Input(85, 35, 25, 25, "Area");
      sSrchArea->textfont(13);
      sSrchArea->align(Fl_Align(FL_ALIGN_TOP));
    } // Fl_Input* sSrchArea
    { sSrchSuffix = new Fl_Input(130, 35, 40, 25, "Suffix");
      sSrchSuffix->textfont(13);
      sSrchSuffix->align(Fl_Align(FL_ALIGN_TOP_LEFT));
    } // Fl_Input* sSrchSuffix
    { btnSearchCancel = new Fl_Button(20, 70, 80, 25, "Cancel");
      btnSearchCancel->callback((Fl_Callback*)cb_btnSearchCancel);
    } // Fl_Button* btnSearchCancel
    { btnSearchOK = new Fl_Return_Button(105, 70, 80, 25, "Search");
      btnSearchOK->callback((Fl_Callback*)cb_btnSearchOK);
    } // Fl_Return_Button* btnSearchOK
    { new Fl_Box(0, 0, 210, 20, "Enter Full Call / Suffix Only");
    } // Fl_Box* o
    winSearchCallsignDialog->set_modal();
    winSearchCallsignDialog->end();
  } // Fl_Double_Window* winSearchCallsignDialog
  return winSearchCallsignDialog;
}

Fl_Double_Window *winSearchNetNbrDialog=(Fl_Double_Window *)0;

Fl_Input *sSrchNetNbr=(Fl_Input *)0;

Fl_Button *btnSearchNetNbrCancel=(Fl_Button *)0;

Fl_Return_Button *btnSearchNetNbrOK=(Fl_Return_Button *)0;

Fl_Double_Window* newSearchNetNbrDialog() {
  { winSearchNetNbrDialog = new Fl_Double_Window(207, 107);
    { sSrchNetNbr = new Fl_Input(80, 30, 50, 25, "Enter Net Number");
      sSrchNetNbr->textfont(13);
      sSrchNetNbr->align(Fl_Align(FL_ALIGN_TOP));
    } // Fl_Input* sSrchNetNbr
    { btnSearchNetNbrCancel = new Fl_Button(20, 70, 80, 25, "Cancel");
      btnSearchNetNbrCancel->callback((Fl_Callback*)cb_btnSearchNetNbrCancel);
    } // Fl_Button* btnSearchNetNbrCancel
    { btnSearchNetNbrOK = new Fl_Return_Button(105, 70, 80, 25, "Search");
      btnSearchNetNbrOK->callback((Fl_Callback*)cb_btnSearchNetNbrOK);
    } // Fl_Return_Button* btnSearchNetNbrOK
    winSearchNetNbrDialog->set_modal();
    winSearchNetNbrDialog->end();
  } // Fl_Double_Window* winSearchNetNbrDialog
  return winSearchNetNbrDialog;
}

Fl_Double_Window *dlgAbout=(Fl_Double_Window *)0;

Fl_Group *lblVersion=(Fl_Group *)0;

static void cb_Thanks(Fl_Return_Button*, void*) {
  dlgAbout->hide ();
}

Fl_Double_Window* newAboutDialog() {
  { dlgAbout = new Fl_Double_Window(320, 184);
    dlgAbout->color((Fl_Color)53);
    { lblVersion = new Fl_Group(5, 5, 310, 105, "xxx:");
      lblVersion->box(FL_ENGRAVED_FRAME);
      lblVersion->align(Fl_Align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE));
      lblVersion->end();
    } // Fl_Group* lblVersion
    { Fl_Return_Button* o = new Fl_Return_Button(100, 150, 100, 25, "Thanks");
      o->callback((Fl_Callback*)cb_Thanks);
    } // Fl_Return_Button* o
    { Fl_Group* o = new Fl_Group(5, 115, 310, 30, "w1hkj@@w1hkj.com");
      o->box(FL_ENGRAVED_FRAME);
      o->align(Fl_Align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE));
      o->end();
    } // Fl_Group* o
    dlgAbout->set_modal();
    dlgAbout->end();
  } // Fl_Double_Window* dlgAbout
  return dlgAbout;
}
